### ISSUE TITLE
Build fails since latest commit

### ISSUE THREAD

**Issue by aminvakil** [google/tsunami-security-scanner#104]
Since commit: https://github.com/google/tsunami-security-scanner/commit/65e84d5

https://github.com/aminvakil/aur/actions/runs/6346178522/job/17249712322#step:11:174
```
FAILURE: Build failed with an exception.

* What went wrong:
Task 'test' not found in root project 'tsunami-security-scanner-plugins'.
```

Command used to build is: `./gradlew shadowJar`

**Comment by McFacePunch** [comment]
Second this, was actually just about to create an issue for this. Quite sad since this has been an issue for over a month.

**Comment by aminvakil** [comment]
AFAICS latest commit of master branch is still https://github.com/google/tsunami-security-scanner/commit/65e84d5, can you elaborate on where it has been reverted?

**Comment by tooryx** [comment]
I think this might have been resolved already. Feel free to reopen if that is not the case.

**Comment by aminvakil** [comment]
Yes, I can also confirm the problem has been resolved, thanks!
