### ISSUE TITLE
AutoValue_PortRange.java:14: error: cannot find symbol

### ISSUE THREAD

**Issue by ehcpdeveloper** [google/tsunami-security-scanner#13]
Got these similar errors:

  symbol:   class ınt
  location: class AutoValue_PortRange
/home/xx/tsunami/repos/tsunami-security-scanner-plugins/google/portscan/nmap/build/generated/sources/annotationProcessor/java/main/com/google/tsunami/plugins/portscan/nmap/client/data/AutoValue_PortRange.java:14: error: cannot find symbol
      ınt endPort) {
      ^
  symbol:   class ınt
  location: class AutoValue_PortRange
/home/xx/tsunami/repos/tsunami-security-scanner-plugins/google/portscan/nmap/build/generated/sources/annotationProcessor/java/main/com/google/tsunami/plugins/portscan/nmap/client/data/AutoValue_PortRange.java:20: error: cannot find symbol
  ınt startPort() {
  ^
  symbol:   class ınt
  location: class AutoValue_PortRange
/home/xx/tsunami/repos/tsunami-security-scanner-plugins/google/portscan/nmap/build/generated/sources/annotationProcessor/java/main/com/google/tsunami/plugins/portscan/nmap/client/data/AutoValue_PortRange.java:25: error: cannot find symbol
  ınt endPort() {
  ^
  symbol:   class ınt
  location: class AutoValue_PortRange
9 errors

I tried with LANG=EN prefix also, same. 
I tried to fix those shown files, but files somehow overwritten and broken again. 

OS info:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04 LTS"
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"

$ java --version
openjdk 11.0.7 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-3ubuntu1)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-3ubuntu1, mixed mode, sharing)

Thanks.

**Comment by magl0** [comment]
Hi, is this still an issue for you? Looks like an localization issue from AutoValue and the generated code uses a dot-less `I`.

**Comment by ehcpdeveloper** [comment]
Yes, still issue. 
I tried some env. variables but no luck.

**Comment by ehcpdeveloper** [comment]
??
