### ISSUE TITLE
ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

### ISSUE THREAD

**Issue by bminossi** [google/tsunami-security-scanner#19]
First of all, Congratz for your amazing project to CyberSec community =-), we really apprecciate it.

I want let you know that maybe it can be catch at the installation proccess to avoid users mistakes.

Thanks for your time

**Comment by bminossi** [comment]
It happens when user dont have java installed

**Comment by hnyuht** [comment]
I have java and java sdk and even edit the system environment and still doesn't work.

**Comment by magl0** [comment]
Closing as the issue has been resolved.
