### ISSUE TITLE
quick_start.sh uses pushd which is not sh compliant

### ISSUE THREAD

**Issue by hannob** [google/tsunami-security-scanner#2]
Your readme recommends running quick_start.sh with sh:
```
sh -c "$(curl -sfL https://raw.githubusercontent.com/google/tsunami-security-scanner/master/quick_start.sh)"
```
The script uses pushd/popd, which aren't standard sh commands. Particularly they're not available in dash, which is the standard sh shell in Ubuntu+Debian.

I recommend either changing the docs to use bash or changing the script to avoid non-standard sh commands.

**Comment by magl0** [comment]
Thanks for reporting the issue. I'll update our document to use bash instead!

**Comment by magl0** [comment]
Commit a75874e updated the document.
