### ISSUE TITLE
java.io.IOException: unexpected end of stream on

### ISSUE THREAD

**Issue by mali44** [google/tsunami-security-scanner#21]
My env java setups on Mac:

- openjdk 14.0.1 2020-04-14
- OpenJDK Runtime Environment (build 14.0.1+7)
- OpenJDK 64-Bit Server VM (build 14.0.1+7, mixed mode, sharing)

While I'm scanning the target with generated command from script, I am encountering the error for every plugin trys:

**WARNING: Unable to query Hadoop Yarn cluster info page. 
java.io.IOException: unexpected end of stream on Connection{IP_ADDRESS:80, proxy=DIRECT hostAddress=/IP_ADDRESS:80 cipherSuite=none protocol=http/1.1}**

(not only for hadoop, happens for every plugins)
thanks for the tool btw :)

**Comment by stamster** [comment]
is OpenJDK supported at all?

**Comment by spaceraccoon** [comment]
This seems to also happen due to the nmap plugin misidentifying HTTPS services as HTTP, leading to web requests to `http://<HOST>:443/` which will cause some servers to reset the connection.

**Comment by mali44** [comment]
I am closing this issue as in the latest version I downlaoded and tried today, is seems fixed. I have not faced any issue, successfully scan and reported. Thanks chaps. :)
