### ISSUE TITLE
Scan a whole subnet?

### ISSUE THREAD

**Issue by braimee** [google/tsunami-security-scanner#22]
Hello,

Pardon what could be a super newb question, but will this scanner only cover a single host at a time?  I didn't see any command line flags for hitting a whole subnet or text file full of hosts?

Thanks,
Brian

**Comment by hooksie1** [comment]
@magl0 mentioned in issue #6 that it only scans one IP. You would use whatever tool you want to scale that up. Google apparently uses GKE which makes sense.

**Comment by braimee** [comment]
Ok thanks much @hooksie1!
