### ISSUE TITLE
就不能搞个简简单单的吗?

### ISSUE THREAD

**Issue by vvring** [google/tsunami-security-scanner#26]
老子搞半天插件都不知道怎么安装.

**Comment by cxliker** [comment]
哥们儿看文档了没

**Comment by vvring** [comment]
> 哥们儿看文档了没

真心没怎么看

**Comment by raystyle** [comment]
实在看不懂此软件的架构。一个单IP命令行扫描工具，Nmap+NSE就能搞定的简单扫描，为什么需要用java封装成如此复杂的代码。

**Comment by haolsh** [comment]
祖安大舞台，有妈你就来

**Comment by 98Kstar** [comment]
除了有google的名号，我没看出来他有什么优秀的地方。

**Comment by magl0** [comment]
I am closing this issue as it is not actionable from dev team.
