### ISSUE TITLE
Kali 2020.2 Exception: Error parsing Nmap result document

### ISSUE THREAD

**Issue by dtrizna** [google/tsunami-security-scanner#27]
Caught exception when initiated scan in accordance with workflow described in README.md:
1. Loaded jupyter in docker (active, verified via netstat, browser);
2. Oneliner for Tsunami installation;
3. Tsunami launch cmd:
```
cd /root/tsunami && \                                                                                                                                                                       
java -cp "tsunami-main-0.0.2-SNAPSHOT-cli.jar:/root/tsunami/plugins/*" \                                                                                                                    
  -Dtsunami-config.location=/root/tsunami/tsunami.yaml \                                                                                                                                    
  com.google.tsunami.main.cli.TsunamiCli \                                                                                                                                                  
  --ip-v4-target=127.0.0.1 \                                                                                                                                                                
  --scan-results-local-output-format=JSON \                                                                                                                                                 
  --scan-results-local-output-filename=/tmp/tsunami-output.json
```

OS - brand fresh Kali in VirtualBox, just from offsec page, version:
```
root@kali:~# cat /etc/*release
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2020.2"
VERSION_ID="2020.2"
VERSION_CODENAME="kali-rolling"
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"
root@kali:~# uname -a
Linux kali 5.5.0-kali2-amd64 #1 SMP Debian 5.5.17-1kali1 (2020-04-21) x86_64 GNU/Linux
```

Nmap and Ncrack versions (up-to-date):
```
Package: nmap
Version: 7.80+dfsg1-2kali2
...
Package: ncrack
Version: 0.7+debian-1
```

Output log fragment with fail information:
```
...
INFO: Executing the following command: '/usr/bin/nmap --unprivileged -Pn -n -sT -sV --version-intensity 5 -T4 --script banner 127.0.0.1 -oX /tmp/nmap8784088487303244937.report'            
Jul 10, 2020 9:20:16 AM com.google.tsunami.plugins.portscan.nmap.client.parser.NmapResultHandler startDocument
INFO: Start parsing Nmap result document.                                                     
Jul 10, 2020 9:20:16 AM com.google.tsunami.plugin.PluginExecutorImpl buildFailedResult        
WARNING: Plugin '/Tsunami Team (tsunami-dev@google.com)/PORT_SCAN/NmapPortScanner/0.1' failed.                                                                                              
Jul 10, 2020 9:20:16 AM com.google.tsunami.workflow.DefaultScanningWorkflow onExecutionError  
SEVERE: Tsunami scan failed, aborting workflow!!!                                             
com.google.tsunami.plugin.PluginExecutionException: (Tsunami error PLUGIN_EXECUTION_ERROR): Plugin execution error on '/Tsunami Team (tsunami-dev@google.com)/PORT_SCAN/NmapPortScanner/0.1'
.                                                                                             
        at com.google.tsunami.plugin.PluginExecutorImpl.wrapException(PluginExecutorImpl.java:100)      
...
```

Full Tsunami output here: https://gist.github.com/dtrizna/74d81e33691ee379193c7032e45b9d93

**Comment by magl0** [comment]
Hi, thanks for reporting the issue. It looks like nmap scan result is missing a required XML attribute (as specified [here](https://github.com/nmap/nmap/blob/a2d44ab1b4facea6dbe2bf0100f87f485e150161/docs/nmap.dtd#L126)). We will fix this soon.

**Comment by yanissyan** [comment]
Same issue  :( 

` Error in custom provider, java.io.FileNotFoundException: Unable to find a valid nmap binary. Make sure Tsunami config contains a valid nmap binary path.
  at com.google.tsunami.plugins.portscan.nmap.NmapPortScannerBootstrapModule.provideNmapBinaryPath(NmapPortScannerBootstrapModule.java:40) (via modules: com.google.tsunami.main.cli.TsunamiCli$TsunamiCliModule -> com.google.tsunami.plugin.PluginLoadingModule -> com.google.tsunami.plugins.portscan.nmap.NmapPortScannerBootstrapModule)
  while locating java.lang.String annotated with @com.google.tsunami.plugins.portscan.nmap.client.NmapBinaryPath()
    for the 1st parameter of com.google.tsunami.plugins.portscan.nmap.client.NmapClient.<init>(NmapClient.java:212)
  while locating com.google.tsunami.plugins.portscan.nmap.client.NmapClient
    for the 1st parameter of com.google.tsunami.plugins.portscan.nmap.NmapPortScanner.<init>(NmapPortScanner.java:81)
  while locating com.google.tsunami.plugins.portscan.nmap.NmapPortScanner
  while locating com.google.tsunami.plugin.TsunamiPlugin annotated with @com.google.inject.internal.Element(setName=,uniqueId=12, type=MAPBINDER, keyType=com.google.tsunami.plugin.PluginDefinition)`
