### ISSUE TITLE
Chore: Compilation warning due to deprecated JsonParser

### ISSUE THREAD

**Issue by rayanht** [google/tsunami-security-scanner#29]
## Description

The following warning appears at build-time:

```
Note: /usr/repos/tsunami-security-scanner/common/src/main/java/com/google/tsunami/common/net/http/HttpResponse.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

According to the [gson documentation](https://javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/JsonParser.html) the `JsonParser` constructor has been deprecated and static methods should be used directly instead.

**Comment by rayanht** [comment]
I branched out incorrectly, will re-submit

**Comment by magl0** [comment]
As mentioned in the PR, the new API `JsonParser.parseString` method was first introduced at gson version `2.8.6`, which is not available at our internal codebase yet. The API will be migrated when our internal dependency evolves.
