### ISSUE TITLE
[FR] Refactor to Golang

### ISSUE THREAD

**Issue by milesflo** [google/tsunami-security-scanner#32]
Semi-serious post, Google & Oracle aren’t on the best of footing.

Why use Java over something more open, for example Google’s own GoLang?

**Comment by dreamcat4** [comment]
To answer your question: it is pretty likely that the initial developer(s) felt most comfortable with Java. They seem to have made a pretty complex and high quality tool with that language. But thinking more broadly I believe the bigger issue here is that the future utility this tool is heavily dependant on other members of the community writing plugins for it. Then it matters if those plugin contributions are required to be written in Java. Well that might put other people off from investing / buying into this new platform.

Other language API bridges are stated 'long term goal' for this project. But there is no ETA currently. Ahem I don't think anybody knows at this point in time. It will take a while before the answer is more clear.

Perhaps another route might be simply to provide a very few (but well made) 'gateway' plugin bridges. To enable the re-use existing plugins from other platforms (for example metasploit or some other competing tools).

Until either of those things happen. Then the most key issue here will be: if a security researcher is working on a new vulnerability. And they want to be writing a plugin at the same time. Well... is the Java requirement going to get in their way / be a significant obstacle for them? Well IDK. But a least there are some well commented examples. Maybe is a 3rd person has a go to making a real detector plugin. Who doesn't know much Java. Then that might do well to answer the question.

**Comment by tooryx** [comment]
We do not plan to rewrite Tsunami in golang at the moment. But we plan to add language server that will provide support for writing plugins in different languages (coming soon: Python).
