### ISSUE TITLE
Integration plugin for https://github.com/infobyte/faraday

### ISSUE THREAD

**Issue by f-amato** [google/tsunami-security-scanner#38]
I would love to write a integration for https://github.com/infobyte/faraday
Where is the report after the scanning? I just running the example run
Sorry but I can't find the path of the report after running the tool.
Thanks!

**Comment by tooryx** [comment]
Hi @f-amato,

Are you still interested in writing an integration plugin for Faraday? Would the idea be to ingest Tsunami's result into Faraday?
You can configure the output file of Tsunami using the command line.

_~tooryx_
