### ISSUE TITLE
Install problem: Downloading gradle-6.5-bin.zip timeout

### ISSUE THREAD

**Issue by birdjumper** [google/tsunami-security-scanner#44]
Hi

Am getting the following error when running:
bash -c "$(curl -sfL https://raw.githubusercontent.com/google/tsunami-security-scanner/master/quick_start.sh)"curl -sfL https://raw.githubusercontent.com/google/tsunami-security-scanner/master/quick_start.sh

Error:
Exception in thread "main" java.io.IOException: Downloading from https://services.gradle.org/distributions/gradle-6.5-bin.zip failed: timeout

I'm using Ubuntu 18 and as I'm behind a company proxy I've setup proxy settings for the system, for docker, curl and wget.

Any idea what I've missed?

Thanks

**Comment by carlspring** [comment]
You will need to set up your Gradle proxy settings as well. Have a look [here](https://stackoverflow.com/questions/5991194/gradle-proxy-configuration).
