### ISSUE TITLE
problem running the test 

### ISSUE THREAD

**Issue by mounaBoo** [google/tsunami-security-scanner#49]
hello, 

I installed the tool as recommanded but when I try to run it it gave me an error 

`Error: Could not find or load main class ` 
`Caused by: java.lang.ClassNotFoundException: `

could anyone help me with that

**Comment by carlspring** [comment]
Hi,

I'm afraid this is error is useless, unless you attach the full stacktrace. You also should provide some more details such as: revision of the `tsunami-security-scanner`, JDK version, Gradle version, OS, etc.
