### ISSUE TITLE
Feature Request:Ability to specify an IP Subnet Range 

### ISSUE THREAD

**Issue by mwahl217** [google/tsunami-security-scanner#50]
Would love to see the ability to scan a larger range-subnet such as

com.google.tsunami.main.cli.TsunamiCli --ip-v4-target=192.168.1.0/24 or

com.google.tsunami.main.cli.TsunamiCli --ip-v4-target=10.0.0.0/16

**Comment by rayanht** [comment]
I have a proposal for this feature, will open a PR in a few moments

**Comment by tooryx** [comment]
Hi,

We do not plan to add this feature for now. See #51 for details.

_~tooryx_
