### ISSUE TITLE
CI Feature request: Run test suite against commits and PRs

### ISSUE THREAD

**Issue by rayanht** [google/tsunami-security-scanner#52]
It'd be nice to verify that new commits don't break any tests and that PRs don't break any existing behaviour

**Comment by magl0** [comment]
Hi @rayanht , thanks for suggestions! This is currently on our roadmap and we are working on setting up CIs for this project. Stay tuned :)

**Comment by magl0** [comment]
This is resolved now. CI has been setup using Github Actions.
