### ISSUE TITLE
Execution failed for task ':compileJava'.

### ISSUE THREAD

**Issue by yu5239** [google/tsunami-security-scanner#55]
> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve com.google.auto.value:auto-value-annotations:1.7.
     Required by:
         project :
         project : > com.google.tsunami:tsunami-common:0.0.1
         project : > com.google.tsunami:tsunami-plugin:0.0.1
         project : > com.google.tsunami:tsunami-common:0.0.1 > com.google.cloud:google-cloud-storage:1.103.1 > com.google.auth:google-auth-library-oauth2-http:0.20.0
      > Could not resolve com.google.auto.value:auto-value-annotations:1.7.
         > Could not get resource 'https://maven-central.storage-download.googleapis.com/repos/central/data/com/google/auto/value/auto-value-annotations/1.7/auto-value-annotations-1.7.pom'.
            > Could not GET 'https://maven-central.storage-download.googleapis.com/repos/central/data/com/google/auto/value/auto-value-annotations/1.7/auto-value-annotations-1.7.pom'.
               > Connect to maven-central.storage-download.googleapis.com:443 [maven-central.storage-download.googleapis.com/34.64.4.112] failed: connect timed out
   > Could not resolve com.google.flogger:flogger:0.5.1.
     Required by:
         project :
         project : > com.google.flogger:google-extensions:0.5.1
         project : > com.google.tsunami:tsunami-common:0.0.1
         project : > com.google.tsunami:tsunami-plugin:0.0.1
      > Could not resolve com.google.flogger:flogger:0.5.1.
         > Could not get resource 'https://maven-central.storage-download.googleapis.com/repos/central/data/com/google/flogger/flogger/0.5.1/flogger-0.5.1.pom'.
            > Could not GET 'https://maven-central.storage-download.googleapis.com/repos/central/data/com/google/flogger/flogger/0.5.1/flogger-0.5.1.pom'.
               > Connect to maven-central.storage-download.googleapis.com:443 [maven-central.storage-download.googleapis.com/34.64.4.112] failed: connect timed out
   > Could not resolve com.google.flogger:flogger-system-backend:0.5.1.
     Required by:
         project :
         project : > com.google.tsunami:tsunami-common:0.0.1
      > Could not resolve com.google.flogger:flogger-system-backend:0.5.1.
         > Could not get resource 'https://maven-central.storage-download.googleapis.com/repos/central/data/com/google/flogger/flogger-system-backend/0.5.1/flogger-system-backend-0.5.1.pom'.
            > Could not GET 'https://maven-central.storage-download.googleapis.com/repos/central/data/com/google/flogger/flogger-system-backend/0.5.1/flogger-system-backend-0.5.1.pom'.
               > Connect to maven-central.storage-download.googleapis.com:443 [maven-central.storage-download.googleapis.com/34.64.4.112] failed: connect timed out
   > Could not resolve com.google.auto.value:auto-value-annotations:1.7.
     Required by:
         project : > com.google.tsunami:tsunami-common:0.0.1 > com.google.truth:truth:1.0.1
      > Could not resolve com.google.auto.value:auto-value-annotations:1.7.
         > Could not get resource 'https://maven-central.storage-download.googleapis.com/repos/central/data/com/google/auto/value/auto-value-annotations/1.7/auto-value-annotations-1.7.pom'.
            > Could not GET 'https://maven-central.storage-download.googleapis.com/repos/central/data/com/google/auto/value/auto-value-annotations/1.7/auto-value-annotations-1.7.pom'.
               > Connect to maven-central.storage-download.googleapis.com:443 [maven-central.storage-download.googleapis.com/34.64.4.112] failed: connect timed out

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 37s
1 actionable task: 1 executed

need help:(

**Comment by magl0** [comment]
Hi @yu5239 , it looks like you cannot connect to the maven repo hosted on googleapis.com. Are you behind a proxy? If not, can you try to remove [these lines](https://github.com/google/tsunami-security-scanner/blob/master/build.gradle#L19-L21) and try again?

**Comment by lsq-connect** [comment]
Have you solved it? I have this problem too

**Comment by MrJacobs9020** [comment]
> Have you solved it? I have this problem too

Hope

**Comment by lsq-connect** [comment]
> > Have you solved it? I have this problem too
> 
> Hope

I have used a proxy, but there is an error in the problem description

**Comment by AgnesQiu** [comment]
> Hi @yu5239 , it looks like you cannot connect to the maven repo hosted on googleapis.com. Are you behind a proxy? If not, can you try to remove [these lines](https://github.com/google/tsunami-security-scanner/blob/master/build.gradle#L19-L21) and try again?

Hi @magl0  I had met same error and I had used a proxy. I had removed the lines you had quoted, but it not fixed the issue. Any other methods ?

**Comment by Adamas24** [comment]
Hi, I have same problem too.
I had used a proxy, Is there any way to get around this error while going through the proxy?

my error(pick up)
 Could not resolve com.google.tsunami:tsunami-common:0.0.1.
         > Could not get resource 'https://repo.maven.apache.org/maven2/com/google/tsunami/tsunami-common/0.0.1/tsunami-common-0.0.1.pom'.
            > Could not GET 'https://repo.maven.apache.org/maven2/com/google/tsunami/tsunami-common/0.0.1/tsunami-common-0.0.1.pom'.
               > http://xxxx.xxx.xxx.co.jp
