### ISSUE TITLE
Kill ncrack credential test when deadline exceeded

### ISSUE THREAD

**Issue by vikasphonsa** [google/tsunami-security-scanner#59]
Hello - I tried to run Tsunami a couple of times against localhost, using curl+quick_start.sh mentioned in docs. It remained stuck in ncrack credential test for hours. Had to kill it. Any thoughts on how to get past this or have it run faster ? 

tsunami-main-0.0.2-SNAPSHOT-cli.jar
MacOS Mojave 10.14.6 
openjdk 14.0.1 2020-04-14

====output====
Jul 19, 2020 10:52:29 PM com.google.tsunami.common.command.CommandExecutor execute
INFO: Executing the following command: '/usr/local/bin/ncrack -T3 --user anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous,anonymous --pass ,123456,password,12345678,qwerty,<list_truncated_here> --pairwise -f ssh://127.0.0.1:22 -oN /var/folders/2_/0b6yg26n0nz2q_7mm65y2j4r981cvs/T/ncrack11164542678979093847.report'

**Comment by wiov** [comment]
I have similar question. The difference is that the program has completed scanning ssh part and entered the telnet part, but it stopped there.

**Comment by magl0** [comment]
Hi, sorry that ncrack was blocking the scanning job. Not much we could do in fixing ncrack binary. Instead I'll open this as a Feature Request for the scanning to kill long running plugins that exceed a configurable deadline.

**Comment by Softsapiens** [comment]
Hi, same experience here

**Comment by frakman1** [comment]
Is there a way to skip tests with tsunami? I thought it might be in tsunami.yaml but I don't see any examples or documentations on how to set this up.
