### ISSUE TITLE
Tsunami scaling abilities

### ISSUE THREAD

**Issue by salehio** [google/tsunami-security-scanner#6]
Hey, I'm just curious if there are any known limits for Tsunami. Is there any experimental data showing it can scale to a certain number of IPs per second? Thanks!

**Comment by tuxevil** [comment]
It would be nice to have more detailed stats

**Comment by magl0** [comment]
Inside Google we leverage [Google Kubernetes Engine](https://cloud.google.com/kubernetes-engine) clusters to scale the scan. Tsunami, as a CLI tool, only scans a single IP, but this also makes horizontal scaling very easy. More concurrent Tsunami processes ~= more throughput on (# of IPs/sec).
