### ISSUE TITLE
How To build and use on windows machine?

### ISSUE THREAD

**Issue by ghostfevil** [google/tsunami-security-scanner#64]
How I can use it on Windows Machine?
Mostly issue is about plugin's Path

**Comment by erikvarga** [comment]
The scanner is mainly intended to run on Linux, so Windows is not supported at the moment. However, there's some [work in progress](https://github.com/google/tsunami-security-scanner/issues/71) to add an official docker image for Tsunami. Once that's done, you could pull the image and run the scanner through Docker on Windows machines.
