### ISSUE TITLE
FAILURE: Build failed with an exception 

### ISSUE THREAD

**Issue by sagarsvkashyap** [google/tsunami-security-scanner#67]
Hello,
I am seeing a new error message,attached is the complete export after running script
Operating system and Dependencies: 
OS: ubuntu 20.04
Nmap: 7.80
Ncrack: 0.7
Java: installed (sudo apt install openjdk-11-jdk)

**EXPORT:**
root@ubuntu:~# sudo bash -c "$(curl -sfL https://raw.githubusercontent.com/google/tsunami-security-scanner/master/quick_start.sh)"

Fetching source code for Tsunami scanner ...
From https://github.com/google/tsunami-security-scanner
 * branch            master     -> FETCH_HEAD
Already up to date.

Fetching source code for Tsunami scanner plugins ...
From https://github.com/google/tsunami-security-scanner-plugins
 * branch            master     -> FETCH_HEAD
Already up to date.

Building all Google plugins ...

Building detectors/credentials/ncrack ...
Downloading https://services.gradle.org/distributions/gradle-6.5-bin.zip
.........10%..........20%..........30%..........40%.........50%..........60%..........70%..........80%.........90%..........100%

Welcome to Gradle 6.5!

Here are the highlights of this release:
 - Experimental file-system watching
 - Improved version ordering
 - New samples

For more details see https://docs.gradle.org/6.5/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

> Task :test
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/root/.gradle/caches/modules-2/files-2.1/com.google.inject/guice/4.2.3/2ea992d6d7bdcac7a43111a95d182a4c42eb5ff7/guice-4.2.3.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

BUILD SUCCESSFUL in 1m 52s
4 actionable tasks: 4 executed

Building detectors/exposedui/hadoop/yarn ...

> Task :test
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/root/.gradle/caches/modules-2/files-2.1/com.google.inject/guice/4.2.3/2ea992d6d7bdcac7a43111a95d182a4c42eb5ff7/guice-4.2.3.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

BUILD SUCCESSFUL in 2s
5 actionable tasks: 5 executed

Building detectors/exposedui/jenkins ...

> Task :test
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/root/.gradle/caches/modules-2/files-2.1/com.google.inject/guice/4.2.3/2ea992d6d7bdcac7a43111a95d182a4c42eb5ff7/guice-4.2.3.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

BUILD SUCCESSFUL in 2s
5 actionable tasks: 5 executed

Building detectors/exposedui/jupyter ...

> Task :test
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/root/.gradle/caches/modules-2/files-2.1/com.google.inject/guice/4.2.3/2ea992d6d7bdcac7a43111a95d182a4c42eb5ff7/guice-4.2.3.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

BUILD SUCCESSFUL in 2s
4 actionable tasks: 4 executed

Building detectors/exposedui/wordpress ...

> Task :test
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/root/.gradle/caches/modules-2/files-2.1/com.google.inject/guice/4.2.3/2ea992d6d7bdcac7a43111a95d182a4c42eb5ff7/guice-4.2.3.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

BUILD SUCCESSFUL in 2s
5 actionable tasks: 5 executed

Building portscan/nmap ...

> Task :compileJava FAILED
/root/tsunami/repos/tsunami-security-scanner-plugins/google/portscan/nmap/src/main/java/com/google/tsunami/plugins/portscan/nmap/NmapPortScanner.java:167: error: incompatible types: Optional<String> cannot be converted to NetworkService
                              && NetworkServiceUtils.isWebService(getServiceNameFromPort(port))) {
                                                                                        ^
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
1 actionable task: 1 executed

Please provide guidance

**Comment by samshuai** [comment]
Same issue :(

![image](https://user-images.githubusercontent.com/1312406/91548615-34c5e600-e958-11ea-9b2d-197210829871.png)


root@auto:~/tsunami# nmap -v
Starting Nmap 7.80 ( https://nmap.org ) at 2020-08-28 09:56 UTC
Read data files from: /usr/bin/../share/nmap
WARNING: No targets were specified, so 0 hosts scanned.
Nmap done: 0 IP addresses (0 hosts up) scanned in 0.04 seconds
           Raw packets sent: 0 (0B) | Rcvd: 0 (0B)
root@auto:~/tsunami# ncrack -v

Starting Ncrack 0.7 ( http://ncrack.org ) at 2020-08-28 09:56 UTC

No services specified!
QUITTING!
root@auto:~/tsunami# javac -version
javac 1.8.0_265

@magl0

**Comment by nurdie** [comment]
I'm seeing the exact same thing on both Ubuntu 18.04 and 20.04

```
Building portscan/nmap ...

> Task :compileJava FAILED
/home/ubuntu/tsunami/repos/tsunami-security-scanner-plugins/google/portscan/nmap/src/main/java/com/google/tsunami/plugins/portscan/nmap/NmapPortScanner.java:167: error: incompatible types: Optional<String> cannot be converted to NetworkService
                              && NetworkServiceUtils.isWebService(getServiceNameFromPort(port))) {
                                                                                        ^
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
1 actionable task: 1 executed
```

```
ubuntu@tsunami---ubuntu18:~/tsunami$ javac -version
javac 11.0.8
ubuntu@tsunami---ubuntu18:~/tsunami$ nmap --version
Nmap version 7.80 ( https://nmap.org )
Platform: x86_64-redhat-linux-gnu
Compiled with: nmap-liblua-5.3.5 openssl-1.0.2s nmap-libssh2-1.8.2 nmap-libz-1.2.11 nmap-libpcre-7.6 nmap-libpcap-1.9.0 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: epoll poll select
```

**Comment by magl0** [comment]
Sorry some of our recent changes broke the build. This should be fixed by https://github.com/google/tsunami-security-scanner-plugins/commit/860536dd48dd9f2c7a2231202a7fd440f3bbf99a.
