### ISSUE TITLE
NMAP not found but installed on my Mac

### ISSUE THREAD

**Issue by spawnrider** [google/tsunami-security-scanner#7]
Hi, 

I have the following issue : 
`1) Error injecting constructor, java.lang.IllegalArgumentException: Binary /usr/bin/nmap do not exist
  at com.google.tsunami.plugins.portscan.nmap.client.NmapClient.<init>(NmapClient.java:211)
  while locating com.google.tsunami.plugins.portscan.nmap.client.NmapClient
    for the 1st parameter of com.google.tsunami.plugins.portscan.nmap.NmapPortScanner.<init>(NmapPortScanner.java:81)
  while locating com.google.tsunami.plugins.portscan.nmap.NmapPortScanner
  while locating com.google.tsunami.plugin.TsunamiPlugin annotated with @com.google.inject.internal.Element(setName=,uniqueId=12, type=MAPBINDER, keyType=com.google.tsunami.plugin.PluginDefinition)`

NMAP was installed using brew on /use/local/bin folder : 
`sh-3.2# which nmap
/usr/local/bin/nmap`

As I have SIP enable on my Mac, I can't modify my /usr/bin folder. 
How can I change the nmap path ? config file ?

**Comment by serinuntius** [comment]
I have a same problem.

**Comment by hirotakaster** [comment]
I got same problem too.  Then I change following files directly and could run tsunami.

- nmap
`$HOME/tsunami/repos/tsunami-security-scanner-plugins/google/portscan/nmap/src/main/java/com/google/tsunami/plugins/portscan/nmap/client/NmapClient.java
`
  private static final String DEFAULT_NMAP_BINARY_PATH = "/usr/bin/nmap";
to 
  private static final String DEFAULT_NMAP_BINARY_PATH = "/usr/local/bin/nmap";

- ncrack
`$HOME/tsunami/repos/tsunami-security-scanner-plugins/google/detectors/credentials/ncrack/src/main/java/com/google/tsunami/plugins/detectors/credentials/ncrack/client/NcrackClient.java
`
  private static final String DEFAULT_NRACK_BINARY_PATH = "/usr/bin/ncrack";
to
  private static final String DEFAULT_NRACK_BINARY_PATH = "/usr/local/bin/ncrack";

**Comment by magl0** [comment]
Hi we've fixed the nmap and ncrack plugin to check both `/usr/bin/nmap` and `/usr/local/bin/nmap` on initialization. You can simply execute the quick start script again to recompile everything and rerun the scanner.

If your nmap/ncrack binaries are installed on different paths, then you could update the `tsunami.yaml` config file accordingly, see the documentations for the [nmap](https://github.com/google/tsunami-security-scanner-plugins/tree/master/google/portscan/nmap#exported-config-values) and [ncrack](https://github.com/google/tsunami-security-scanner-plugins/tree/master/google/detectors/credentials/ncrack#exported-config-values) plugins for details.

**Comment by kaidotdev** [comment]
FYI: I wrote Dockerfile.

```
FROM ubuntu:18.04 AS builder

RUN apt-get update -y && apt-get upgrade -y

RUN apt-get install -y git openjdk-11-jdk && rm -rf /var/lib/apt/lists/*

ADD https://api.github.com/repos/google/tsunami-security-scanner/compare/master...HEAD /dev/null
RUN git clone https://github.com/google/tsunami-security-scanner /opt/tsunami-security-scanner
ADD https://api.github.com/repos/google/tsunami-security-scanner-plugins/compare/master...HEAD /dev/null
RUN git clone https://github.com/google/tsunami-security-scanner-plugins /opt/tsunami-security-scanner-plugins

WORKDIR /opt/tsunami-security-scanner
RUN ./gradlew shadowJar

WORKDIR /opt/tsunami-security-scanner-plugins/google
RUN ./build_all.sh

FROM ubuntu:18.04

RUN apt-get update -y && apt-get upgrade -y

RUN apt-get install -y openjdk-11-jdk nmap ncrack && rm -rf /var/lib/apt/lists/*

COPY --from=builder /opt/tsunami-security-scanner-plugins/google/build/plugins /opt/tsunami/plugins
COPY --from=builder /opt/tsunami-security-scanner/main/build/libs/tsunami-main-*-cli.jar /opt/tsunami/tsunami-main-cli.jar
COPY --from=builder /opt/tsunami-security-scanner/tsunami.yaml /opt/tsunami/tsunami.yaml

WORKDIR /opt/tsunami
ENTRYPOINT ["java", "-cp", "tsunami-main-cli.jar:/opt/tsunami/plugins/*", "-Dtsunami-config.location=/opt/tsunami/tsunami.yaml", "com.google.tsunami.main.cli.TsunamiCli", "--scan-results-local-output-format=JSON", "--scan-results-local-output-filename=/dev/stdout"]
CMD ["--ip-v4-target=127.0.0.1"]
```
