### ISSUE TITLE
Using Tsunami to scan app running on a specific port

### ISSUE THREAD

**Issue by teavanist** [google/tsunami-security-scanner#73]
Hi, 
Is there a way to specify in Tsunami to not scan all the port but to proceed with only a specific port? I have an application that runs on port (say 7000). I want Tsunami to scan only https://ipaddress:7000/ 
Is this possible?

**Comment by erikvarga** [comment]
Hi,
You can use the --port-ranges-target option to specify ports or ranges of ports to scan, e.g. --port-ranges-target=7000
