### ISSUE TITLE
Hangs after completing ncrack

### ISSUE THREAD

**Issue by frakman1** [google/tsunami-security-scanner#77]
I built the Docker container from the Dockerfile today and ran it against a docker container running metasploitable.
Docker image can be found at Dockerhub under `frakman1/tsunami:latest`

Metasploitable Target:
```
docker run --name metasploitable -it tleemcjr/metasploitable2:latest sh -c "/bin/services.sh && bash
```
Tsunami pointing at Target's IP:
```
docker run --rm  --network="host" --name=tsunami -v "$(pwd)/logs":/usr/tsunami/logs frakman1/tsunami:latest --ip-v4-target=172.17.0.2
```
Tsunami actually hung at one of the ncrack's at the target's telnet test (port 23)
I killed it and a bunch of other ncrack processes because they too would hang using:
 
```
kill `pidof ncrack`
```

I then left it alone. It continued to the end of the ncrack tests but then it just sat there. The docker container is still running so it's not like it crashed or exited.

Log:

```
Mar 04, 2021 8:32:22 PM com.google.tsunami.common.command.CommandExecutor execute
INFO: Executing the following command: '/usr/bin/ncrack -T3 --user azureuser,azureuser,azureuser,azureuser,azureuser,azureuser,azureuser,azureuser,azureuser,azureuser,azureuser,azureuser,azureuser,azureuser,azureuser,azureuser,azureuser,azureuser --pass cheese,amanda,summer,love,ashley,6969,nicole,chelsea,biteme,matthew,access,yankees,987654321,dallas,austin,thunder,taylor,matrix --pairwise -f vnc://172.17.0.2:5900 -oN /tmp/ncrack8296972980122334100.report'
Mar 04, 2021 8:32:25 PM com.google.tsunami.plugins.detectors.credentials.ncrack.NcrackWeakCredentialDetector detect
INFO: Ncrack weak credential detection finished in 46.25 min.
```
The Tsunami docker image is very light with no common tools like `ps`,`top`, `ifconfig`, `ip` or even `vi` so I can't tell what it's doing, if anything.

This is 100% reproducible. Not sure what else to try.

**Comment by gaby** [comment]
I'm also having a similar issue, specially when a scan fails to find any vulnerability it just sits there without exiting.

**Comment by tooryx** [comment]
Hi folks,

I suspect that this issue might now be obsolete. Are you still encountering this issue or is it okay if I close this bug?

_~tooryx_

**Comment by gaby** [comment]
@tooryx I havent used the tool in a while. What did help was having tools to debug inside the container as proposed in #82 a while ago

**Comment by tooryx** [comment]
In that case, I will close this specific issue for now. Feel free to reopen if you encounter the same issues in the future.
We can continue discussion specific to the debugging tools in the PR.

_~tooryx_
