### ISSUE TITLE
Docker build fails with "Exception in thread "main" java.io.IOException: Downloading from https://services.gradle.org/distributions/gradle-6.5-bin.zip failed: timeout"

### ISSUE THREAD

**Issue by huornlmj** [google/tsunami-security-scanner#91]
**docker build -t tsunami .** results in the following failure

> Building detectors/credentials/cve20177615 ...
> Downloading https://services.gradle.org/distributions/gradle-6.5-bin.zip
> Exception in thread "main" java.io.IOException: Downloading from https://services.gradle.org/distributions/gradle-6.5-bin.zip failed: timeout
>         at org.gradle.wrapper.Download.downloadInternal(Download.java:106)
>         at org.gradle.wrapper.Download.download(Download.java:66)
>         at org.gradle.wrapper.Install$1.call(Install.java:68)
>         at org.gradle.wrapper.Install$1.call(Install.java:48)
>         at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
>         at org.gradle.wrapper.Install.createDist(Install.java:48)
>         at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
>         at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
> Caused by: java.net.SocketTimeoutException: Connect timed out
>         at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546)
>         at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
>         at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:339)
>         at java.base/java.net.Socket.connect(Socket.java:603)
>         at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:290)
>         at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
>         at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
>         at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
>         at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
>         at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
>         at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:177)
>         at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
>         at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
>         at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:163)
>         at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
>         at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
>         at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
>         at org.gradle.wrapper.Download.downloadInternal(Download.java:83)
>         ... 7 more
> The command '/bin/sh -c chmod +x build_all.sh     && ./build_all.sh' returned a non-zero code: 1

**Comment by nikhil6624** [comment]
Hi @huornlmj , May I start working on this issue?

**Comment by tooryx** [comment]
I suspect this might have to do with proxies and be a transient error. Given that this issue is a bit old, I am closing it for now, but feel free to reopen if you are still encountering the issue.
