### ISSUE TITLE
HttpClient.sendAsIs should not allow only GET methods

### ISSUE THREAD

**Issue by hh-hunter** [google/tsunami-security-scanner#92]
https://github.com/google/tsunami-security-scanner/blob/b570bb14c08a02651074fa5c30360674fca9fcc4/common/src/main/java/com/google/tsunami/common/net/http/HttpClient.java#L79-L81

I'm writing a plugin for this, but I've discovered that sendAsIs currently only supports GET requests, and the target plugin I'm writing needs to use POST requests, which will prevent me from detecting the vulnerability point.

**Comment by magl0** [comment]
Ack, we'll add more HTTP method support in `sendAsIs`.
