### ISSUE TITLE
IP address range

### ISSUE THREAD

**Issue by daveBuccheri** [google/tsunami-security-scanner#96]
Hello everybody, is it possible to modify the Dockerfile in this way into CMD

--ip-v4-target=192.168.10.2
in
--ip-v4-target=192.168.10.0/24

?
I need to scan all the network and not a single IP address

Thanks

**Comment by tooryx** [comment]
Hi,

We do not plan to add this feature for now. See https://github.com/google/tsunami-security-scanner/pull/51 for details.

_~tooryx_
